Repository tbe-team/raybot, pull requests merged in 2025-03, with the labels that each got.

#16 fix: add write permission for Github token
  .github/workflows/release-dev.yml
Labels: ✏️ Feature, ☢️ Bug

#17 ci: update build and release
  .github/workflows/build.yml
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
Labels: 🧹 Updates

#18 ci: fix missing go path when build
  .github/workflows/release.yml
Labels: ☢️ Bug

#19 ci: add write contents permission
  .github/workflows/release.yml
Labels: ✏️ Feature

#20 fix: unmarshal state type
  internal/controller/picserial/handler/sync_state_handler.go
  internal/controller/picserial/handler/sync_state_test.go
  internal/controller/picserial/service.go
  internal/controller/picserial/service_test.go
Labels: ☢️ Bug

#23 docs: update state and serial msg format
  docs/vi/application_state.md
  docs/vi/pic_response.md
Labels: documentation, 🧹 Updates, 📒 Documentation

#28 docs: add pic serial command
  docs/vi/pic_response.md
  docs/vi/pic_serial_command.md
Labels: ✏️ Feature, 📒 Documentation

#36 feat: add sidebar
  ui/src/App.vue
  ui/src/assets/main.css
  ui/src/components/ui/button/Button.vue
  ui/src/components/ui/button/index.ts
  ui/src/components/ui/input/Input.vue
  ui/src/components/ui/input/index.ts
  ui/src/components/ui/separator/Separator.vue
  ui/src/components/ui/separator/index.ts
  ui/src/components/ui/sheet/Sheet.vue
  ui/src/components/ui/sheet/SheetClose.vue
  ui/src/components/ui/sheet/SheetContent.vue
  ui/src/components/ui/sheet/SheetDescription.vue
  ui/src/components/ui/sheet/SheetFooter.vue
  ui/src/components/ui/sheet/SheetHeader.vue
  ui/src/components/ui/sheet/SheetTitle.vue
  ui/src/components/ui/sheet/SheetTrigger.vue
  ui/src/components/ui/sheet/index.ts
  ui/src/components/ui/sidebar/Sidebar.vue
  ui/src/components/ui/sidebar/SidebarContent.vue
  ui/src/components/ui/sidebar/SidebarFooter.vue
  ui/src/components/ui/sidebar/SidebarGroup.vue
  ui/src/components/ui/sidebar/SidebarGroupAction.vue
  ui/src/components/ui/sidebar/SidebarGroupContent.vue
  ui/src/components/ui/sidebar/SidebarGroupLabel.vue
  ui/src/components/ui/sidebar/SidebarHeader.vue
  ui/src/components/ui/sidebar/SidebarInput.vue
  ui/src/components/ui/sidebar/SidebarInset.vue
  ui/src/components/ui/sidebar/SidebarMenu.vue
  ui/src/components/ui/sidebar/SidebarMenuAction.vue
  ui/src/components/ui/sidebar/SidebarMenuBadge.vue
  ui/src/components/ui/sidebar/SidebarMenuButton.vue
  ui/src/components/ui/sidebar/SidebarMenuButtonChild.vue
  ui/src/components/ui/sidebar/SidebarMenuItem.vue
  ui/src/components/ui/sidebar/SidebarMenuSkeleton.vue
  ui/src/components/ui/sidebar/SidebarMenuSub.vue
  ui/src/components/ui/sidebar/SidebarMenuSubButton.vue
  ui/src/components/ui/sidebar/SidebarMenuSubItem.vue
  ui/src/components/ui/sidebar/SidebarProvider.vue
  ui/src/components/ui/sidebar/SidebarRail.vue
  ui/src/components/ui/sidebar/SidebarSeparator.vue
  ui/src/components/ui/sidebar/SidebarTrigger.vue
  ui/src/components/ui/sidebar/index.ts
  ui/src/components/ui/sidebar/utils.ts
  ui/src/components/ui/skeleton/Skeleton.vue
  ui/src/components/ui/skeleton/index.ts
  ui/src/components/ui/tooltip/Tooltip.vue
  ui/src/components/ui/tooltip/TooltipContent.vue
  ui/src/components/ui/tooltip/TooltipProvider.vue
  ui/src/components/ui/tooltip/TooltipTrigger.vue
  ui/src/components/ui/tooltip/index.ts
  ui/src/layouts/main-layout/Logo.vue
  ui/src/layouts/main-layout/MainLayout.vue
  ui/src/layouts/main-layout/menu.ts
  ui/src/router/index.ts
  ui/src/views/About.vue
  ui/src/views/Home.vue
  ui/src/views/System.vue
  ui/tailwind.config.js
Labels: ✏️ Feature

#40 fix: remove charging state
  docs/vi/application_state.md
  docs/vi/pic_response.md
  internal/controller/picserial/handler/sync_state_handler.go
  internal/controller/picserial/handler/sync_state_handler_integration_test.go
  internal/model/robot_state.go
  internal/service/robot.go
  internal/service/serviceimpl/robot.go
Labels: 🧹 Updates, ☢️ Bug

#38 feat: add pic serial command
  .mockery.yml
  Makefile
  cmd/raybot/grpc/run.go
  cmd/raybot/http/run.go
  cmd/raybot/pic/run.go
  docs/vi/pic_response.md
  go.mod
  go.sum
  internal/application/application.go
  internal/config/manager.go
  internal/config/mocks/manager.gen.go
  internal/controller/grpc/converter/robot_state.go
  internal/controller/grpc/handler/drive_motor_handler.go
  internal/controller/grpc/handler/lift_motor_handler.go
  internal/controller/grpc/service.go
  internal/controller/http/service.go
  internal/controller/picserial/handler/command_ack_handler.go
  internal/controller/picserial/handler/command_ack_handler_test.go
  internal/controller/picserial/handler/sync_state_handler.go
  internal/controller/picserial/handler/sync_state_handler_integration_test.go
  internal/controller/picserial/handler/sync_state_handler_test.go
  internal/controller/picserial/serial/client.go
  internal/controller/picserial/serial/mocks/client.gen.go
  internal/controller/picserial/service.go
  internal/controller/picserial/service_test.go
  internal/model/pic_serial_command.go
  internal/repository/mocks/pic_serial_command_repository.gen.go
  internal/repository/mocks/repository.gen.go
  internal/repository/mocks/robot_state_repository.gen.go
  internal/repository/pic_serial_command.go
  internal/repository/repoimpl/pic_serial_command.go
  internal/repository/repoimpl/repository.go
  internal/repository/repository.go
  internal/service/mocks/pic_service.gen.go
  internal/service/mocks/robot_service.gen.go
  internal/service/mocks/service.gen.go
  internal/service/mocks/system_service.gen.go
  internal/service/pic.go
  internal/service/robot.go
  internal/service/service.go
  internal/service/serviceimpl/pic.go
  internal/service/serviceimpl/pic_test.go
  internal/service/serviceimpl/robot_test.go
  internal/service/serviceimpl/service.go
  internal/service/serviceimpl/system.go
  internal/service/serviceimpl/system_test.go
  pkg/log/log.go
Labels: ✏️ Feature

#43 fix(http): add missing http config response
  internal/controller/http/converter/system.go
  internal/controller/http/handler/system_handler_test.go
Labels: ✏️ Feature, ☢️ Bug

#48 chore: remove duplicate renovate config
  renovate.json
Labels: 🧹 Updates

#59 fix: fix npm pkg manager
  .github/renovate.json5
Labels: ☢️ Bug

#61 chore: add ui lint ci
  .github/workflows/ui-lint.yml
Labels: ✏️ Feature

#62 fix(ci): add cache dependency path for pnpm in ui lint workflow
  .github/workflows/ui-lint.yml
Labels: ✏️ Feature

#67 chore(http): add recovery and logging middleware
  internal/controller/http/middleware/logging.go
  internal/controller/http/middleware/recoverer.go
  internal/controller/http/service.go
Labels: ✏️ Feature

#72 fix: remove redundant rule
  .github/renovate.json5
Labels: 🧹 Updates, ☢️ Bug

#73 chore: update renovate rules
  .github/renovate.json5
Labels: 🧹 Updates

#74 feat: add restart application HTTP endpoint
  Makefile
  api/openapi/components/schemas/health.yml
  api/openapi/gen/openapi.yml
  api/openapi/openapi.yml
  api/openapi/paths/health.yml
  api/openapi/paths/system@restart.yml
  internal/controller/http/handler/handler.go
  internal/controller/http/handler/health_handler.go
  internal/controller/http/handler/system_handler.go
  internal/controller/http/handler/system_handler_test.go
  internal/controller/http/oas/gen/openapi.gen.go
  internal/service/mocks/system_service.gen.go
  internal/service/serviceimpl/system.go
  internal/service/system.go
Labels: ✏️ Feature

#42 feat(ui): add system config page
  ui/.env.example
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/App.vue
  ui/src/api/system.ts
  ui/src/components/ui/collapsible/Collapsible.vue
  ui/src/components/ui/collapsible/CollapsibleContent.vue
  ui/src/components/ui/collapsible/CollapsibleTrigger.vue
  ui/src/components/ui/collapsible/index.ts
  ui/src/components/ui/form/FormControl.vue
  ui/src/components/ui/form/FormDescription.vue
  ui/src/components/ui/form/FormItem.vue
  ui/src/components/ui/form/FormLabel.vue
  ui/src/components/ui/form/FormMessage.vue
  ui/src/components/ui/form/index.ts
  ui/src/components/ui/form/injectionKeys.ts
  ui/src/components/ui/form/useFormField.ts
  ui/src/components/ui/label/Label.vue
  ui/src/components/ui/label/index.ts
  ui/src/components/ui/select/Select.vue
  ui/src/components/ui/select/SelectContent.vue
  ui/src/components/ui/select/SelectGroup.vue
  ui/src/components/ui/select/SelectItem.vue
  ui/src/components/ui/select/SelectItemText.vue
  ui/src/components/ui/select/SelectLabel.vue
  ui/src/components/ui/select/SelectScrollDownButton.vue
  ui/src/components/ui/select/SelectScrollUpButton.vue
  ui/src/components/ui/select/SelectSeparator.vue
  ui/src/components/ui/select/SelectTrigger.vue
  ui/src/components/ui/select/SelectValue.vue
  ui/src/components/ui/select/index.ts
  ui/src/components/ui/switch/Switch.vue
  ui/src/components/ui/switch/index.ts
  ui/src/components/ui/tabs/Tabs.vue
  ui/src/components/ui/tabs/TabsContent.vue
  ui/src/components/ui/tabs/TabsList.vue
  ui/src/components/ui/tabs/TabsTrigger.vue
  ui/src/components/ui/tabs/index.ts
  ui/src/composables/use-system-config.ts
  ui/src/env.d.ts
  ui/src/lib/http.ts
  ui/src/router/index.ts
  ui/src/types/system-config.ts
  ui/src/views/System.vue
  ui/src/views/system/SystemView.vue
  ui/src/views/system/components/system-config-form/GrpcCollapsible.vue
  ui/src/views/system/components/system-config-form/HttpCollapsible.vue
  ui/src/views/system/components/system-config-form/LogCollapsible.vue
  ui/src/views/system/components/system-config-form/PicCollapsible.vue
  ui/src/views/system/components/system-config-form/SystemConfigForm.vue
  ui/src/views/system/components/system-config-form/index.ts
  ui/src/views/system/components/system-config-form/shema.ts
  ui/vite.config.ts
Labels: ✏️ Feature

#79 fix(build): Fix unknown field Setpgid when building on Windows
  Makefile
  internal/service/serviceimpl/system.go
Labels: ☢️ Bug

#88 feat: persist robot state
  .mockery.yml
  Makefile
  cmd/raybot/main.go
  go.mod
  go.sum
  internal/application/application.go
  internal/application/path.go
  internal/config/config.go
  internal/config/manager.go
  internal/config/mocks/manager.gen.go
  internal/controller/picserial/handler/sync_state_handler_integration_test.go
  internal/controller/picserial/handler/sync_state_handler_test.go
  internal/repository/mocks/robot_state_repository.gen.go
  internal/repository/repoimpl/repository.go
  internal/repository/repoimpl/robot_state.go
  internal/repository/robot_state.go
  internal/service/serviceimpl/pic.go
  internal/service/serviceimpl/pic_test.go
  internal/service/serviceimpl/robot.go
  internal/service/serviceimpl/robot_test.go
  internal/service/serviceimpl/service.go
  internal/service/serviceimpl/system.go
  internal/service/serviceimpl/system_test.go
  internal/storage/db/db.go
  internal/storage/db/error_utils.go
  internal/storage/db/migrate.go
  internal/storage/db/migration/20250313015139_robot_state.sql
  internal/storage/db/mocks/provider.gen.go
  internal/storage/db/mocks/sqldb.gen.go
  internal/storage/db/provider.go
  internal/storage/db/sqlc/db.go
  internal/storage/db/sqlc/models.go
  internal/storage/db/sqlc/robot_state.sql
  internal/storage/db/sqlc/robot_state.sql.go
  internal/storage/db/sqlc/sqlc.yml
  internal/storage/file/local_file.go
Labels: ✏️ Feature

#91 feat: Add robot state API
  api/openapi/components/schemas/state.yml
  api/openapi/gen/openapi.yml
  api/openapi/openapi.yml
  api/openapi/paths/robot-state.yml
  internal/controller/http/converter/robot_state.go
  internal/controller/http/handler/handler.go
  internal/controller/http/handler/robot_state_handler.go
  internal/controller/http/handler/robot_state_handler_test.go
  internal/controller/http/oas/gen/openapi.gen.go
  internal/controller/rfid/service.go
  internal/model/robot_state.go
  internal/repository/repoimpl/robot_state.go
  internal/storage/db/migration/20250313015139_robot_state.sql
Labels: ✏️ Feature

#97 feat: Add docker
  Makefile
  docker/raybot/Dockerfile
  internal/controller/http/handler/robot_state_handler.go
Labels: ✏️ Feature

#109 refactor: change boolean enable fields to uint8 in command data
  internal/service/serviceimpl/pic.go
Labels: 🧹 Updates

#111 fix: add missing deps when build binary
  .github/workflows/release.yml
Labels: ✏️ Feature, ☢️ Bug

#113 fix: update release workflow to standardize artifact naming conventions
  .github/workflows/release.yml
Labels: 🧹 Updates, ☢️ Bug

#60 docs: add ESP serial command
  docs/vi/esp_response.md
  docs/vi/esp_serial_command.md
  docs/vi/pic_response.md
  docs/vi/pic_serial_command.md
Labels: ✏️ Feature, ☢️ Bug, 📒 Documentation

#150 fix: add gen-proto command to gen-all in Makefile
  Makefile
Labels: ✏️ Feature, ☢️ Bug

#161 chore(ci): fix download artifacts
  .github/workflows/release.yml
Labels: ☢️ Bug

#162 fix: use pattern instead of name in download artifacts step
  .github/workflows/release.yml
Labels: ☢️ Bug

#163 fix(ci): remove download artifacts pattern
  .github/workflows/release.yml
Labels: 🧹 Updates, ☢️ Bug

#164 chore: update download artifact step
  .github/workflows/release.yml
Labels: 🧹 Updates

#169 feat(command service): handle stale commands on startup
  internal/service/serviceimpl/command/service.go
Labels: ✏️ Feature
