Repository tbe-team/raybot, pull requests merged in 2025-04, with the labels that each got.

#208 Docs: add battery response in esp_respone.md
  docs/vi/esp_response.md
  docs/vi/esp_serial_command.md
Labels: ✏️ Feature

#227 fix: add started at field for command
  Makefile
  api/openapi/components/schemas/command.yml
  api/openapi/openapi.gen.yml
  internal/config/config.go
  internal/handlers/http/command_handler.go
  internal/handlers/http/gen/openapi_api.gen.go
  internal/services/command/command.go
  internal/services/command/commandimpl/repository.go
  internal/services/command/commandimpl/service.go
  internal/services/command/models.go
  internal/storage/db/migration/20250414063753_command_add_started_at.sql
  internal/storage/db/sqlc/command.sql
  internal/storage/db/sqlc/command.sql.go
  internal/storage/db/sqlc/models.go
Labels: ✏️ Feature, ☢️ Bug

#239 feat: add context cancel when serial write
  internal/hardware/espserial/client.go
  internal/hardware/espserial/controller.go
  internal/hardware/picserial/client.go
  internal/hardware/picserial/controller.go
  internal/services/cargo/cargoimpl/service.go
  internal/services/drivemotor/drivemotorimpl/service.go
  internal/services/liftmotor/liftmotorimpl/service.go
Labels: ✏️ Feature

#253 chore: update license and readme
  LICENSE
  README.md
Labels: 🧹 Updates

#263 feat: add error code API
  api/openapi/components/schemas/error-code.yml
  api/openapi/openapi.gen.yml
  api/openapi/openapi.yml
  api/openapi/paths/error-codes.yml
  cmd/raybot/standalone/http.go
  internal/application/application.go
  internal/handlers/http/error_code_handler.go
  internal/handlers/http/gen/openapi_api.gen.go
  internal/handlers/http/service.go
  internal/services/apperrorcode/app_error_code.go
  internal/services/apperrorcode/apperrorcodeimpl/error_codes.go
  internal/services/apperrorcode/apperrorcodeimpl/service.go
  internal/services/apperrorcode/models.go
Labels: ✏️ Feature

#266 feat: add cron job service, auto delete old command
  cmd/raybot/standalone/jobs.go
  cmd/raybot/standalone/run.go
  go.mod
  go.sum
  internal/application/application.go
  internal/config/config.go
  internal/config/cron.go
  internal/handlers/jobs/delete_old_command_handler.go
  internal/handlers/jobs/service.go
  internal/services/command/command.go
  internal/services/command/commandimpl/repository.go
  internal/services/command/commandimpl/service.go
  internal/services/command/mocks/repository.gen.go
  internal/storage/db/sqlc/command.sql
  internal/storage/db/sqlc/command.sql.go
  raybot-config.yml
Labels: ✏️ Feature

#284 fix: stop drive motor after reaching target location
  internal/services/command/executor/move_to_executor.go
Labels: ☢️ Bug

#287 refactor: remove cors middleware
  go.mod
  go.sum
  internal/handlers/http/middleware/cors.go
  internal/handlers/http/middleware/logging.go
  internal/handlers/http/service.go
Labels: 🧹 Updates

#298 feat: add architecture image, add CORS middleware
  docs/architecture.png
  docs/developer-guide.md
  go.mod
  go.sum
  internal/handlers/http/middleware/cors.go
  internal/handlers/http/service.go
Labels: ✏️ Feature

#303 feat(cloud): add gRPC command service
  .mockery.yml
  Makefile
  api/proto/command/v1/command.proto
  buf.gen.yaml
  cmd/raybot/standalone/cloud.go
  go.mod
  go.sum
  internal/handlers/cloud/cloudtest/client_conn.go
  internal/handlers/cloud/cloudtest/cloud_server.go
  internal/handlers/cloud/cloudtest/tunnel_authn_interceptor.go
  internal/handlers/cloud/command_handler.go
  internal/handlers/cloud/command_handler_integration_test.go
  internal/handlers/cloud/gen/command/v1/command.pb.go
  internal/handlers/cloud/gen/command/v1/command_grpc.pb.go
  internal/handlers/cloud/grpcerr/grpc_err.go
  internal/handlers/cloud/grpcerr/grpc_err_test.go
  internal/handlers/cloud/interceptor/error.go
  internal/handlers/cloud/interceptor/logging.go
  internal/handlers/cloud/interceptor/recovery.go
  internal/handlers/cloud/interceptor/reverse_credentials_integration_test.go
  internal/handlers/cloud/service.go
  internal/handlers/cloud/service_integration_test.go
  internal/services/command/executor/router.go
  internal/services/command/mocks/service.gen.go
  internal/storage/db/db.go
  pkg/eventbus/noop.go
Labels: ✏️ Feature
