Repository tbe-team/raybot, pull requests merged in 2025-05, with the labels that each got.

#324 feat: add logging to file
  .gitignore
  api/openapi/components/schemas/config.yml
  api/openapi/openapi.gen.yml
  go.mod
  go.sum
  internal/application/application.go
  internal/config/log.go
  internal/handlers/cloud/cloudtest/client_conn.go
  internal/handlers/cloud/service_integration_test.go
  internal/handlers/http/config_handler.go
  internal/handlers/http/gen/openapi_api.gen.go
  internal/logging/fanout_handler.go
  internal/logging/logging.go
  internal/services/command/executor/executor_test.go
  internal/services/drivemotor/drive_motor.go
  pkg/log/config.go
  pkg/log/log.go
  raybot-config.yml
Labels: ✏️ Feature

#329 feat: enhance command execution logging
  internal/services/command/executor/executor.go
Labels: ✏️ Feature

#338 refactor: rewrite serial `Read` method and add unit test
  internal/handlers/espserial/service.go
  internal/handlers/picserial/service.go
  internal/hardware/espserial/README.md
  internal/hardware/espserial/client.go
  internal/hardware/espserial/client_test.go
  internal/hardware/espserial/controller_test.go
  internal/hardware/espserial/mock_serial_port.go
  internal/hardware/picserial/client.go
  internal/hardware/picserial/client_test.go
  internal/hardware/picserial/controller_test.go
  internal/hardware/picserial/mock_serial_port.go
Labels: 🧹 Updates, ✏️ Feature

#353 feat: implement cancel active commands created by cloud
  .gitignore
  internal/application/application.go
  internal/handlers/cloud/cloudtest/client_conn.go
  internal/handlers/cloud/service.go
  internal/handlers/event/cloud_event_handler.go
  internal/services/command/command.go
  internal/services/command/commandimpl/repository.go
  internal/services/command/commandimpl/service.go
  internal/services/command/commandimpl/service_integration_test.go
  internal/services/command/mocks/repository.gen.go
  internal/services/command/mocks/service.gen.go
  internal/services/command/processinglockimpl/processing_lock.go
  internal/services/command/processinglockimpl/processing_lock_test.go
  internal/storage/db/db.go
  internal/storage/db/sqlc/command.sql
  internal/storage/db/sqlc/command.sql.go
Labels: ✏️ Feature

#361 fix: emergency stop call and current command state should be CANCELED
  internal/application/application.go
  internal/services/command/command.go
  internal/services/command/commandimpl/service.go
  internal/services/command/commandimpl/service_integration_test.go
  internal/services/command/mocks/service.gen.go
  internal/services/command/processinglockimpl/processing_lock_test.go
  internal/services/emergency/emergencyimpl/service.go
  internal/services/emergency/emergencyimpl/service_test.go
Labels: ☢️ Bug

#368 feat: stop lift motor when cancel `CARGO_LIFT`, `CARGO_LOWER` command
  internal/hardware/picserial/controller.go
  internal/hardware/picserial/controller_test.go
  internal/services/command/executor/cargo_lift_executor.go
  internal/services/command/executor/cargo_lower_executor.go
  internal/services/liftmotor/liftmotorimpl/service.go
Labels: ✏️ Feature

#369 feat: update configuration of speed limit
  docs/vi/pic_serial_command.md
Labels: 🧹 Updates, ✏️ Feature

#374 refactor: improve error handling in root application
  cmd/raybot/standalone/run.go
Labels: 🧹 Updates

#381 fix: command executor hook use canceled context
  .mockery.yml
  go.mod
  internal/application/application.go
  internal/handlers/cloud/cloudtest/client_conn.go
  internal/services/appstate/app_state.go
  internal/services/appstate/appstateimpl/repository.go
  internal/services/cargo/mocks/service.gen.go
  internal/services/command/command.go
  internal/services/command/commandimpl/running_cmd_repository.go
  internal/services/command/commandimpl/service.go
  internal/services/command/commandimpl/service_integration_test.go
  internal/services/command/commandimpl/service_test.go
  internal/services/command/commandimpl/verify_main_test.go
  internal/services/command/executor/cargo_check_qr_executor.go
  internal/services/command/executor/cargo_close_executor.go
  internal/services/command/executor/cargo_lift_executor.go
  internal/services/command/executor/cargo_lower_executor.go
  internal/services/command/executor/cargo_open_executor.go
  internal/services/command/executor/executor.go
  internal/services/command/executor/executor_test.go
  internal/services/command/executor/move_backward_executor.go
  internal/services/command/executor/move_forward_executor.go
  internal/services/command/executor/move_to_executor.go
  internal/services/command/executor/route.go
  internal/services/command/executor/route_test.go
  internal/services/command/executor/router.go
  internal/services/command/executor/scan_location_executor.go
  internal/services/command/executor/service.go
  internal/services/command/executor/service_test.go
  internal/services/command/executor/stop_movement_executor.go
  internal/services/command/executor/verify_main_test.go
  internal/services/command/executor/wait_executor.go
  internal/services/command/mocks/executor_service.gen.go
  internal/services/command/mocks/running_command_repository.gen.go
  internal/services/command/models.go
  pkg/eventbus/mocks/publisher.gen.go
Labels: ☢️ Bug

#387 refactor: update time parsing and formatting to RFC3339Nano
  internal/services/battery/batteryimpl/setting_repository.go
  internal/services/cargo/cargoimpl/repository.go
  internal/services/command/commandimpl/repository.go
  internal/services/location/locationimpl/repository.go
Labels: 🧹 Updates

#382 docs: update distance sensor for dectect object
  docs/vi/esp_response.md
Labels: 🧹 Updates, 📒 Documentation

#391 fix: stop obstacle detection goroutine when target height is reached
  internal/services/command/executor/cargo_lower_executor.go
Labels: ☢️ Bug

#411 feat: integrate Buf schema registry
  .github/workflows/bsr-ci.yml
  .github/workflows/spelling.yml
  buf.yaml
Labels: ✏️ Feature

#412 feat: checking cargo door is open before execute command
  internal/services/cargo/cargo.go
  internal/services/cargo/cargoimpl/service.go
  internal/services/cargo/mocks/service.gen.go
  internal/services/command/executor/cargo_close_executor.go
  internal/services/command/executor/cargo_open_executor.go
Labels: ✏️ Feature

#415 feat: enhance command inputs, remove cargo config
  api/openapi/components/schemas/command.yml
  api/openapi/components/schemas/config.yml
  api/openapi/openapi.gen.yml
  api/openapi/openapi.yml
  api/openapi/paths/configs@cargo.yml
  api/proto/command/v1/command.proto
  api/proto/command/v1/inputs.proto
  api/proto/command/v1/outputs.proto
  api/proto/command/v1/service.proto
  buf.gen.yaml
  internal/application/application.go
  internal/config/cargo.go
  internal/config/config.go
  internal/handlers/cloud/command_handler.go
  internal/handlers/cloud/command_handler_integration_test.go
  internal/handlers/cloud/gen/command/v1/command.pb.go
  internal/handlers/cloud/gen/command/v1/inputs.pb.go
  internal/handlers/cloud/gen/command/v1/outputs.pb.go
  internal/handlers/cloud/gen/command/v1/service.pb.go
  internal/handlers/cloud/gen/command/v1/service_grpc.pb.go
  internal/handlers/http/command_handler.go
  internal/handlers/http/config_handler.go
  internal/handlers/http/gen/openapi_api.gen.go
  internal/services/cargo/cargo.go
  internal/services/cargo/cargoimpl/service.go
  internal/services/cargo/mocks/service.gen.go
  internal/services/command/executor/cargo_close_executor.go
  internal/services/command/executor/cargo_lift_executor.go
  internal/services/command/executor/cargo_lower_executor.go
  internal/services/command/executor/cargo_open_executor.go
  internal/services/command/executor/move_backward_executor.go
  internal/services/command/executor/move_forward_executor.go
  internal/services/command/executor/move_to_executor.go
  internal/services/command/executor/service.go
  internal/services/command/executor/service_test.go
  internal/services/command/inputs.go
  internal/services/config/config.go
  internal/services/config/configimpl/service.go
  raybot-config.yml
Labels: 🧹 Updates, ✏️ Feature

#422 fix: stop drive motor should handle with current motor direction
  internal/hardware/picserial/controller.go
  internal/hardware/picserial/controller_test.go
  internal/services/drivemotor/drivemotorimpl/service.go
Labels: ☢️ Bug

#430 fix: avoid duplicate uart message when write
  internal/hardware/espserial/client.go
  internal/hardware/picserial/client.go
Labels: ☢️ Bug

#431 refactor: update job handling and command execution logic
  cmd/raybot/standalone/jobs.go
  go.mod
  go.sum
  internal/config/cron.go
  internal/handlers/event/command_created_handler.go
  internal/handlers/event/service.go
  internal/handlers/jobs/delete_old_command_handler.go
  internal/handlers/jobs/execute_command_handler.go
  internal/handlers/jobs/service.go
  internal/services/command/command.go
  internal/services/command/commandimpl/service.go
  internal/services/command/commandimpl/service_test.go
  internal/services/command/mocks/service.gen.go
Labels: 🧹 Updates

#442 feat(hardware): add command ACK handling
  api/openapi/components/schemas/config.yml
  api/openapi/openapi.gen.yml
  go.mod
  go.sum
  internal/application/application.go
  internal/config/hardware.go
  internal/events/uart_cmd_ack.go
  internal/handlers/http/config_handler.go
  internal/handlers/http/gen/openapi_api.gen.go
  internal/handlers/picserial/ack_handler.go
  internal/handlers/picserial/service.go
  internal/hardware/controller/battery_controller.go
  internal/hardware/controller/battery_controller_test.go
  internal/hardware/controller/cargo_controller.go
  internal/hardware/controller/cargo_controller_test.go
  internal/hardware/controller/cargo_door_controller.go
  internal/hardware/controller/cargo_door_controller_test.go
  internal/hardware/controller/controller.go
  internal/hardware/controller/drive_motor_controller.go
  internal/hardware/controller/drive_motor_controller_test.go
  internal/hardware/controller/esp_cmd.go
  internal/hardware/controller/mock_event_bus.go
  internal/hardware/controller/options.go
  internal/hardware/controller/pic_cmd.go
  internal/hardware/controller/utils.go
  internal/hardware/controller/utils_test.go
  internal/hardware/controller/verify_main_test.go
  internal/hardware/espserial/client.go
  internal/hardware/espserial/controller.go
  internal/hardware/espserial/controller_test.go
  internal/hardware/picserial/client.go
  internal/hardware/picserial/controller.go
  internal/hardware/picserial/controller_test.go
  internal/services/cargo/cargoimpl/service.go
  internal/services/drivemotor/drivemotorimpl/service.go
  internal/services/liftmotor/liftmotorimpl/service.go
  raybot-config.yml
Labels: ✏️ Feature
